### ISSUE TITLE
Не работают транзакции внутри put

### ISSUE THREAD

**Issue by zerkalica** [Riim/cellx#23]
С optimistic updates бывает на fail одного атома, надо откатить 10 других, как сделать это в транзакции?

```js
let a = new cellx.Cell(1)

let b = new cellx.Cell(1, {
  put(val, push, fail) {
     setTimeout(() => {
        cellx.transact(() => {
            a.set(3)
            fail(new Error('some error'))
        })
     }, 0)
  }
})

cellx.configure({asynchronous: false})
const c = new cellx.Cell(() => a.get() + b.get())
c.subscribe((err, {value}) => {
  console.log('c.subscribe: ' + (err ? err.message : '') + ', val: ' + value)
})
console.log('c.get:'+ c.get())
b.set(2)

/*
"c.get:2"
"Error: some error
    at cellx.transact (vudoyofase.js:8:18)
    at Function.transaction (https://npmcdn.com/cellx@1.6.74/dist/cellx.min.js:1:17210)
    at setTimeout (vudoyofase.js:6:15)"
"c.subscribe: some error, val: undefined"
"c.subscribe: , val: 4"
*/

```

http://jsbin.com/wajoxapuvo/edit?js,console

Думаю, аналогично для pull

**Comment by Riim** [comment]
Поправил в `1.6.76`.
